services:
    cervantes-db:
        container_name: cervantes-db
        networks:
            - cervantes
        image: mesq/cervantes-postgres:latest
        restart: unless-stopped
        environment:
            POSTGRES_DB: cervantes
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: EnUnLugarDeLaMancha1547
        volumes:
            - cervantes_postgres:/var/lib/postgresql/data
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres -d cervantes"]
          interval: 5s
          timeout: 5s
          retries: 5
          start_period: 10s
    
    cervantes-app:
        container_name: cervantes-app
        networks:
            - cervantes
        image: mesq/cervantes:latest
        depends_on:
          cervantes-db:
            condition: service_healthy
        restart: unless-stopped
        ports:
            - "443:8081"
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:443
            - ASPNETCORE_HTTPS_PORT=443
            - ASPNETCORE_Kestrel__Certificates__Default__Password=CervantesCert
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/cervantes.pfx
        volumes:
            - ./appsettings.json:/app/appsettings.json
            - ./https:/https:ro

networks:
    cervantes:
        driver:  bridge

volumes:
    cervantes_postgres:
