version: '3.8'
services:
    cervantes-db:
        container_name: cervantes-db
        networks:
            - cervantes
        image: mesq/cervantes-postgres:latest
        restart: unless-stopped
        expose:
            - "5432"
        environment:
            POSTGRES_DB: cervantes
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: EnUnLugarDeLaMancha1547
    
    cervantes-app:
        container_name: cervantes-app
        networks:
            - cervantes
        image: mesq/cervantes:latest
        depends_on:
            - cervantes-db
        restart: unless-stopped
        ports:
            - "443:8081"
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:443
            - ASPNETCORE_HTTPS_PORT=443
            - ASPNETCORE_Kestrel__Certificates__Default__Password=CervantesCert
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/cervantes.pfx
        volumes:
            - ./appsettings.json:/app/appsettings.json
            - ./https:/https:ro

networks:
    cervantes:
        driver:  bridge
